[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-api-gateway.amazonaws.com/dev"
  NEXTAUTH_SECRET = "your-secret-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-api-gateway.amazonaws.com/prod"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://your-api-gateway.amazonaws.com/dev"