version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "localstack-data:/var/lib/localstack"
volumes:
  localstack-data:
