name: Deploy Hospital Management System

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite ejecución manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./proyecto
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'
          cache-dependency-path: './proyecto/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Pre-deploy validation
        run: |
          echo "Validating serverless configuration..."
          npx serverless print --stage prod

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "Deploying to AWS..."
          npx serverless deploy --stage prod --verbose
